[project]
name = "upback"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.2",
    "asgiref>=3.11.0",
    "flasgger>=0.9.7.1",
    "flask>=3.1.2",
    "flask-restx>=1.3.2",
    "uuid>=1.30",
    "uvicorn>=0.40.0",
]

[project.scripts]
start = "app:main"
